{% set name = "normi" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/normi-{{ version }}.tar.gz
  sha256: 1e8aab7b66c370b4933cc394279ea2f8ee209c3724c121f681fa7ebf6a68af96

build:
  noarch: python
  entry_points:
    - normi = normi.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - scipy
    - click >=8.0.0
    - beartype >=0.10.4
    - tqdm
    - scikit-learn >=1.0.0
    - typing-extensions >=3.9.0

test:
  imports:
    - normi
  commands:
    - pip check
    - normi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/moldyn/NorMI
  summary: Estimator for Normalized Mutual Information
  license: MIT
  license_file: LICENSE
  doc_url: https://moldyn.github.io/NorMI/

extra:
  recipe-maintainers:
    - braniii
